export const scroll: string;
export const root: string;
export const editRoot: string;
export const edit: string;
export const title: string;
export const description: string;
export const shape1: string;
export const shape2: string;
export const shape3: string;
export const shape4: string;
export const shape5: string;
export const image: string;
export const hidden: string;
export const editText: string;
export const active: string;
export const preview: string;
interface Namespace {
  addBtn: string;
  scroll: string;
  root: string;
  editRoot: string;
  edit: string;
  title: string;
  description: string;
  block: string;
  editBlock: string;
  image: string;
  hidden: string;
  editText: string;
  active: string;
  preview: string;
}
declare const stylesModule: Namespace;
export default stylesModule;
