export enum SceneNames {
  Base = 'base',
  Base2 = 'base2',
  Base3 = 'base3',
  Quiz1 = 'quiz1',
  FullImage = 'fullImage',
  FullVideo = 'fullVideo',
  MultipleTiles = 'multipletiles',
  MultipleTiles4 = 'multipletiles4',
  MultipleTiles4FullImage = 'multipletiles4FullImg',
  MultipleTiles6FullImage = 'multipletiles6FullImg',
  MultipleTiles8FullImage = 'multipletiles8FullImg',
  MultipleTiles6 = 'multipletiles6',
  MultipleTiles8 = 'multipletiles8',
  FullImageWithButton = 'fullImageWithButton',
  Tiles = 'tiles',
  Spellbee = 'spellbee',
  Parallax1 = 'parallax1',
  Scene15 = 'scene15',
  Atomi = 'atomi',
  Twocando = 'twocando',
  WordGuess = 'wordGuess',
  Counting = 'counting',
  MathBase = 'mathBase',
  TenFrames1 = 'tenFrames1',
}
