export const scroll: string;
export const root: string;
export const editRoot: string;
export const edit: string;
export const background1: string;
export const background2: string;
export const title: string;
export const description: string;
export const image1: string;
export const image2: string;
export const image3: string;
export const image4: string;
export const image: string;
export const hidden: string;
export const editText: string;
export const active: string;
export const preview: string;
interface Namespace {
  scroll: string;
  root: string;
  editRoot: string;
  edit: string;
  title: string;
  description: string;
  image1: string;
  image2: string;
  image3: string;
  image4: string;
  hidden: string;
  editText: string;
  active: string;
  preview: string;
  view: string;
}
declare const stylesModule: Namespace;
export default stylesModule;
